#!/bin/bash

# symbols
DEGREES=$'\xc2\xb0'

# end-points
NSW_OBS=ftp://ftp.bom.gov.au/anon/gen/fwo/IDN60920.xml
NSW_FCAST=ftp://ftp.bom.gov.au/anon/gen/fwo/IDN11020.xml

TAS_OBS=ftp://ftp.bom.gov.au/anon/gen/fwo/IDT60920.xml
TAS_FCAST=ftp://ftp.bom.gov.au/anon/gen/fwo/IDT16000.xml

NT_OBS=ftp://ftp.bom.gov.au/anon/gen/fwo/IDD60920.xml
NT_FCAST=ftp://ftp.bom.gov.au/anon/gen/fwo/IDD10207.xml

QLD_OBS=ftp://ftp.bom.gov.au/anon/gen/fwo/IDQ60920.xml
QLD_FCAST=ftp://ftp.bom.gov.au/anon/gen/fwo/IDQ10606.xml

SA_OBS=ftp://ftp.bom.gov.au/anon/gen/fwo/IDS60920.xml
SA_FCAST=ftp://ftp.bom.gov.au/anon/gen/fwo/IDS11055.xml

VIC_OBS=ftp://ftp.bom.gov.au/anon/gen/fwo/IDV60920.xml
VIC_FCAST=ftp://ftp.bom.gov.au/anon/gen/fwo/IDV10750.xml

WA_OBS=ftp://ftp.bom.gov.au/anon/gen/fwo/IDW60920.xml
WA_FCAST=ftp://ftp.bom.gov.au/anon/gen/fwo/IDW13010.xml


# cached files
# if file cached, return it
# else curl end-point, cache file, return it
function get_file() {
    CACHE="$1_C"
    RES="${!CACHE}"
    if [ ${RES:+1} ]; then
        echo "$RES"
    else
        printf -v "$CACHE" "%s" "$(curl -s ${!1})"
        echo "${!CACHE}"
    fi
}


# pretty print header
function print_header() {
    rl="$(echo -n $1 | wc -c)"
    ll="$(echo -n $2 | wc -c)"
    sl="$(echo -n $3 | wc -c)"

    printf %"s" "+";
    for i in $(seq 1 $(($ll + $rl + $sl + 4))); do printf %"s" "-"; done;
    printf %"s\n" "+"
    printf %"s\n" "| $1 $3 $2 |"
    printf %"s" "+";
    for i in $(seq 1 $(($ll + $rl + $sl + 4))); do printf %"s" "-"; done;
    printf %"s\n" "+"
}


#TODO: allow format param to show details for each station
# stations
function list_stations() {
    DATA="$(echo $1 | xpath -q -e '//station/@description')"
    if [ $2 ]; then
        print_header "Stations"
    fi
    for i in "$DATA"
    do
        #strip leading text and double quotes
        echo "$i" | sed -e 's/\sdescription=//g' -e 's/\"//g'
    done
    if [ $2 ]; then
        printf %"s\n"
    fi
}


#TODO: allow format param to show details for each district
# forecast districts
function list_forecast_districts() {
    DATA="$(echo $1 | xpath -q -e '//area[@type='"'public-district'"']/@description')"
    if [ $2 ]; then
        print_header "Forecast districts"
    fi
    for i in "$DATA"
    do
        #strip leading text and double quotes
        echo "$i" | sed -e 's/\sdescription=//g' -e 's/\"//g'
    done
    if [ $2 ]; then
        printf %"s\n"
    fi
}


#TODO: allow format param to show details for each location
# forecast locations
function list_forecast_locations() {
    DATA="$(echo $1 | xpath -q -e '//area[@type='"'location'"']/@description')"
    if [ $2 ]; then
        print_header "Forecast locations"
    fi
    for i in "$DATA"
    do
        #strip leading text and double quotes
        echo "$i" | sed -e 's/\sdescription=//g' -e 's/\"//g'
    done
    if [ $2 ]; then
        printf %"s\n"
    fi
}

#TODO: pass in format????
# synoptic forecast (region)
function forecast_synoptic() {
    DATA="$(echo $1 | xpath -q -e '//area[@aac='"'$2'"']')"
    l="$(echo $DATA | xpath -q -e '//area/@description')"
    #strip leading text and double quotes
    location="$(echo "$l" | sed -e 's/\sdescription=//g' -e 's/\"//g')"
    if [ $3 ]; then
        print_header "Synoptic forecast" "$location" "-"
    fi
    printf %"s\n" "$(echo $DATA | xpath -q -e '//text[@type='"'synoptic_situation'"']/text()')"
    if [ $3 ]; then printf %"s\n"; fi
}


#TODO: pass in index [0..3] (0 today, 1 tomorrow, etc)
#TODO: pass in format????
# district forecast
function forecast_district() {
    DATA="$(echo $1 | xpath -q -e '//area[@description='"'$2'"']/forecast-period[@index='"'0'"']')"
    #strip leading text and double quotes
    location="$(echo "$2" | sed -e 's/\sdescription=//g' -e 's/\"//g')"
    if [ $3 ]; then
        print_header "District forecast" "$location" "-"
    fi
    printf %"s\n" "$(echo $DATA | xpath -q -e '//text[@type='"'forecast'"']/text()')"
    if [ $3 ]; then printf %"s\n"; fi
}


#FIXME: it appears that there sometimes isn't an index at 0 (perhaps after a certain time at night?)
#TODO: pass in index [0..3] (0 today, 1 tomorrow, etc)
#TODO: pass in format
# location forecast
function forecast_location() {
    DATA="$(echo $1 | xpath -q -e '//area[@description='"'$2'"']/forecast-period[@index='"'0'"']')"
    #strip leading text and double quotes
    location="$(echo "$2" | sed -e 's/\sdescription=//g' -e 's/\"//g')"
    precis="$(echo $DATA | xpath -q -e '//text[@type='"'precis'"']/text()')"
    temp="$(echo $DATA | xpath -q -e '//element[@type='"'air_temperature_maximum'"']/text()')"
    if [ $3 ]; then
        print_header "Location forecast" "$location" "-"
    fi
    printf "%s %s%s%s\n" "$precis" "$temp" "$DEGREES" "C"
    if [ $3 ]; then printf %"s\n"; fi
}


#function extract_obs() {
#    "$(echo $1 | xpath -q -e '//element[@type='"'$2'"']/text()')"
#}


#TODO: optionally get fcast data if requested in format string
function obs_station() {
    declare -A obs #bash 4
    OBS_F=$(get_file "$1"_OBS)

    #FCAST_F=$(get_file "$1"_FCAST)

    DATA="$(echo $o | xpath -q -e '//station[@description='"'$2'"']')"
    #raw XML
    #printf "%s\n" $DATA


    obs=(
         #["a"]=forecast precis # not observation!
         #["A"]=forecast max temp # not observation!
         ["b"]
         ["B"]
         ["c"]="$(echo $DATA | xpath -q -e '//element[@type='"'cloud'"']/text()')" #txt
         #["c"]=extract_obs $DATA $2
         ["C"]="$(echo $DATA | xpath -q -e '//element[@type='"'cloud_oktas'"']/text()')" #?
         ["d"]="$(echo $DATA | xpath -q -e '//element[@type='"'dew_point'"']/text()')" #C
         ["D"]="$(echo $DATA | xpath -q -e '//element[@type='"'wind_dir'"']/text()')" #dir
         ["e"]="$(echo $DATA | xpath -q -e '//element[@type='"'wind_dir_deg'"']/text()')" #deg
         ["E"]="$(echo $DATA | xpath -q -e '//element[@type='"'maximum_gust_kmh'"']/text()')" #km/h
         ["f"]="$(echo $DATA | xpath -q -e '//element[@type='"'maximum_gust_spd'"']/text()')" #knots
         ["F"]="$(echo $DATA | xpath -q -e '//element[@type='"'maximum_gust_dir'"']/text()')" #dir
         ["g"]="$(echo $DATA | xpath -q -e '//element[@type='"'gust_kmh'"']/text()')" #km/h
         ["G"]="$(echo $DATA | xpath -q -e '//element[@type='"'wind_gust_spd'"']/text()')" #knots
         ["h"]="$(echo $DATA | xpath -q -e '//element[@type='"'rel-humidity'"']/text()')" #%
         ...
         ["m"]="$(echo $DATA | xpath -q -e '//element[@type='"'minimum_air_temperature'"']/text()')" #C
         ["M"]="$(echo $DATA | xpath -q -e '//element[@type='"'maximum_air_temperature'"']/text()')" #C
         ...
         ["O"]="$(echo $DATA | xpath -q -e '//element[@type='"'qnh_pres'"']/text()')" #hPa
         ["p"]="$(echo $DATA | xpath -q -e '//element[@type='"'pres'"']/text()')" #hPa
         ["P"]="$(echo $DATA | xpath -q -e '//element[@type='"'msl_pres'"']/text()')" #hPa
         ...
         ["q"]="$(echo $DATA | xpath -q -e '//element[@type='"'rain_hour'"']/text()')" #mm
         ["Q"]="$(echo $DATA | xpath -q -e '//element[@type='"'rain_ten'"']/text()')" #mm
         ["r"]="$(echo $DATA | xpath -q -e '//element[@type='"'rainfall'"']/text()')" #mm
         ["R"]="$(echo $DATA | xpath -q -e '//element[@type='"'rainfall_24hr'"']/text()')" #mm
         ["s"]="$(echo $DATA | xpath -q -e '//element[@type='"'wind_spd_kmh'"']/text()')" km/h
         ["S"]="$(echo $DATA | xpath -q -e '//element[@type='"'wind_spd'"']/text()')" #knots
         ["t"]="$(echo $DATA | xpath -q -e '//element[@type='"'air_temperature'"']/text()')" #C
         ["T"]="$(echo $DATA | xpath -q -e '//element[@type='"'apparent_temp'"']/text()')" #C
         ["u"]="$(echo $DATA | xpath -q -e '//element[@type='"'delta_t'"']/text()')" #C
         ...
         ["v"]="$(echo $DATA | xpath -q -e '//element[@type='"'vis_km'"']/text()')" #km
         ...
         ["z"]="$(echo $DATA | xpath -q -e 'string(//period/@time-local)')"
         ["Z"]="$(echo $DEGREES)"
        )

    echo "${obs[@]}"

    echo "${obs[b]}"

    #echo "$DATA"
    #strip leading text and double quotes
    #location="$(echo "$2" | sed -e 's/\sdescription=//g' -e 's/\"//g')"
    #precis="$(echo $DATA | xpath -q -e '//text[@type='"'precis'"']/text()')"
    #temp="$(echo $DATA | xpath -q -e '//element[@type='"'air_temperature_maximum'"']/text()')"
    #if [ $3 ]; then
    #    print_header "Location forecast" "$location" "-"
    #fi
    #printf "%s %s%s%s\n" "$precis" "$temp" "$DEGREES" "C"
    #if [ $3 ]; then printf %"s\n"; fi
}



for ARG in "$@"
do
    K=$(echo $ARG | cut -f1 -d=)
    V=$(echo $ARG | cut -f2 -d=)
    case "$K" in
        --pretty)              pretty=true;;
        --stations)            stations=true;;
        --state)               state="$V";;

        --forecast-districts)  forecast_districts=true;;
        --forecast-locations)  forecast_locations=true;;
        --forecast-synoptic)   forecast_synoptic=true;;
        --forecast-district)   forecast_district="$V";;
        --forecast-location)   forecast_location="$V";;

        --station)             station="$V";;

        --format)              format="$V";;
        *)
    esac
done



# list stations
if [ "$stations" = true ] && [ ${state:+1} ]; then
    f=$(get_file "$state"_OBS)
    if [ ${pretty:+1} ]; then
        list_stations "$f" "$pretty"
    else
        list_stations "$f"
    fi
fi


# list forecast districts
if [ "$forecast_districts" = true ] && [ ${state:+1} ]; then
    f=$(get_file "$state"_FCAST)
    if [ ${pretty:+1} ]; then
        list_forecast_districts "$f" "$pretty"
    else
        list_forecast_districts "$f"
    fi
fi


# list forecast locations
if [ "$forecast_locations" = true ] && [ ${state:+1} ]; then
    f=$(get_file "$state"_FCAST)
    if [ ${pretty:+1} ]; then
        list_forecast_locations "$f" "$pretty"
    else
        list_forecast_locations "$f"
    fi
fi


# synoptic forecast
if [ "$forecast_synoptic" = true ] && [ ${state:+1} ]; then
    f=$(get_file "$state"_FCAST)
    if [ ${pretty:+1} ]; then
        forecast_synoptic "$f" "$state"_FA001 "$pretty"
    else
        forecast_synoptic "$f" "$state"_FA001
    fi
fi


# district forecast
if [ ${forecast_district:+1} ] && [ ${state:+1} ]; then
    f=$(get_file "$state"_FCAST)
    if [ ${pretty:+1} ]; then
        forecast_district "$f" "$forecast_district" "$pretty"
    else
        forecast_district "$f" "$forecast_district"
    fi
fi


# location forecast
if [ ${forecast_location:+1} ] && [ ${state:+1} ]; then
    f=$(get_file "$state"_FCAST)
    if [ ${pretty:+1} ]; then
        forecast_location "$f" "$forecast_location" "$pretty"
    else
        forecast_location "$f" "$forecast_location"
    fi
fi


# station observations
if [ ${station:+1} ] && [ ${state:+1} ]; then
    if [ ${pretty:+1} ]; then
        obs_station "$state" "$station" "$pretty"
    else
        obs_station "$state" "$station" "$format"
    fi
fi



# --state (required)
# Usage: --state=TAS
# Options: [NSW,TAS,NT,QLD,SA,VIC,WA]

# --stations
# Usage: --stations

# --forecast-districts
# Usage: --forecast-districts

# --forecast-locations
# Usage: --forecast-locations

# --forecast-synoptic
# Usage: --forecast-synoptic

# --pretty
# Usage: --pretty

# --format
# Usage: --format="temp-apparent: %a%DC temp-actual:%A%DC "








#STATION_FCAST_TODAY="$(echo $FCAST | xpath -q -e '//area[@description='"'Hobart'"']/forecast-period[@index='"'0'"']')"
#STATION_FCAST_TOMORROW="$(echo $FCAST | xpath -q -e '//area[@description='"'Hobart'"']/forecast-period[@index='"'1'"']')"
#STATION_FCAST_OVERMORROW="$(echo $FCAST | xpath -q -e '//area[@description='"'Hobart'"']/forecast-period[@index='"'2'"']')"

#temp_max_fcast="$(echo $STATION_FCAST_TODAY | xpath -q -e 'string(//element[@type='"'air_temperature_maximum'"'])')"
#echo $temp_max_fcast
#precis_fcast="$(echo $STATION_FCAST_TODAY | xpath -q -e 'string(//text[@type='"'precis'"'])')"
#echo $precis_fcast

#echo $STATION_FCAST_TODAY
#echo $STATION_FCAST_TOMORROW
#echo $STATION_FCAST_OVERMORROW



#FCAST="$(xpath -q -e '//area[@description='"'Hobart'"']/forecast-period' test-forecast.xml)"
#FCAST="$(xpath -q -e '//area[@description='"'Hobart'"']/forecast-period[@index='"'0'"']' test-forecast.xml)"
#echo $FCAST

#fcast_today="$(echo $FCAST | xpath -q -e '//forecast-period[@index='"'0'"']')"
#echo $fcast_today

#temp_fcast_today="$(echo $FCAST | xpath -q -e '//element[@type='"'air_temperature_maximum'"']/text()')"
#echo $temp_fcast_today
#precis_fcast_today="$(echo $FCAST | xpath -q -e '//text[@type='"'precis'"']/text()')"
#echo $precis_fcast_today
